### ISSUE TITLE
Communication protocol

### ISSUE THREAD

**Issue by gorstj** [mrQ000/layz-rc#1]
Can you give an overview of the serial protocol?

**Comment by mrQ000** [comment]
just have a look at the last page of the [project presentation slides](https://docs.google.com/presentation/d/e/2PACX-1vTHQPsuV6sXKc5gxL9crg099udq97GZqN0jf2Jnf2mCJcU21wUM8zd_1vZSeGWA5wYvWniveEIPkd5f/pub?start=false&loop=false&delayms=3000&slide=id.g4643aef857_0_257)

**Comment by FunFR** [comment]
Hi,

Can you tell me if the serial com is 3.3v or 5v please ?

Thx

**Comment by mrQ000** [comment]
supply provided by IOC to DSP, as well as data lines, are all 5V

**Comment by lmcd** [comment]
If you don't need the LED strip or push button, it is possible to connect IOC 5v directly to the controller USB line as a power source?

**Comment by mrQ000** [comment]
> If you don't need the LED strip or push button, it is possible to connect IOC 5v directly to the controller USB line as a power source?

theoretically yes - but i would not recommend to do so, since i don't know the specs of the IOC's 5V output. the controller inserted between DSP and IOC communicates via GSM which means current spikes of up to 2A, with fairly steep signal edges - which may cause EMC issues, too.

**Comment by lmcd** [comment]
Thanks for the useful information, and all your hard work reverse engineering this.
I'm looking at other, smaller controllers like the `ESP8266` which seems to have 2x UART, and WiFi connectivity - which is enough for me.

Power consumption of this chip has been shown to spike at ~435 mA. Do you think the IOC's 5V output power will have a better chance at sustaining this? If you think it's still a risk, what's a reliable way of determining the quality of the IOC's power?

https://www.ondrovo.com/a/20170207-esp-consumption/

**Comment by mrQ000** [comment]
i did not look into the IOC's power supply, but some simple thoughts about:
- the 5V output has mainly to drive the IOC's and DSP's control logic - this may mean some 100mA, typ. <1A
- adding another 450mA may even double the consumption

you can just try it and have a look at the 5V supply to see if it drops under your extra load by some 10mV. further you should keep an eye on the temperature of the supply unit.
but you risk to destroy your supply unit with the need to fix some voltage regulator (or just a fuse if you are lucky). 
for me this does not stand for, because it's quite easy to integrate a cheap mobile phone USB charger solving the supply affairs.

**Comment by lmcd** [comment]
I see. Thanks again - I'm fairly new to electronics.
I'm guessing branching a USB power supply off the main cable is a big no-no, considering the huge draw of the heaters?

**Comment by mrQ000** [comment]
heaters draw approx. 2000W, your controller approx. 5 to 10W incl. peripherals and conversion losses - e.g. it's about just 0.5% (10/2000) of additional power -> that does not matter

**Comment by lmcd** [comment]
So it's perfectly safe to y-split the incoming power cable? One out to the heater, pump, etc, and the other out to a 5v/2a USB power supply?

**Comment by mrQ000** [comment]
yes - the incoming power cables ends (in my unit) at a screw connector - thats a good location to connect the 5V supply.

disclaimer: take care about isolation, disconnect from mains before opening the housing...
